# ============================================================================
# 🔬 CONFIGURATION D'OPTIMISATION OPTUNA
# ============================================================================
# 
# Ce fichier définit la configuration complète pour l'optimisation Optuna
# d'une stratégie de trading.
#
# Structure:
#   - strategy: Définition de la stratégie à optimiser
#   - config: Configuration générale (symboles, période, capital)
#   - optuna: Paramètres de l'optimiseur Optuna
#   - param_grid: Grille des paramètres à optimiser
#   - profiles: Profils prédéfinis (quick/dev/prod)
#
# Usage:
#   python scripts/run_optuna_from_yaml.py optimization_configs/ma_strategy.yaml
#   python scripts/run_optuna_from_yaml.py optimization_configs/ma_strategy.yaml --profile prod
#
# ============================================================================

# ----------------------------------------------------------------------------
# 🎯 STRATÉGIE À OPTIMISER
# ----------------------------------------------------------------------------
strategy:
  # Chemin Python complet vers la classe de stratégie
  # Format: module.sous_module.NomClasse
  class: "strategies.marsi.MaRSI"
  
  # Nom de la stratégie (pour les logs et rapports)
  name: "MaRSI"
  
  # Description optionnelle
  description: "Stratégie combinant MA, RSI avec trailing stop"

# ----------------------------------------------------------------------------
# ⚙️ CONFIGURATION GÉNÉRALE
# ----------------------------------------------------------------------------
config:
  # Symboles à trader (liste)
  symbols:
    - AAPL
    - MSFT
    - GOOGL
    - AMZN
    - QQQ
    - NKE
    - TTE.PA
    - SPY
    - OR.PA
  
  # Période de test
  period:
    start: "2021-01-01"
    end: "2025-01-01"
  
  # Capital initial en USD
  capital: 100000

# ----------------------------------------------------------------------------
# 🔬 PARAMÈTRES OPTUNA
# ----------------------------------------------------------------------------
optuna:
  # Nombre d'essais (trials)
  # Plus élevé = meilleure exploration mais plus long
  # Recommandé: 50-200 pour tests, 500-1000+ pour production
  n_trials: 200
  
  # Timeout en secondes (null = pas de limite)
  # Exemple: 3600 = 1 heure
  timeout: null
  
  # Algorithme de sampling
  # Options:
  #   - tpe: Tree-structured Parzen Estimator (recommandé, intelligent)
  #   - random: Échantillonnage aléatoire
  #   - cmaes: Covariance Matrix Adaptation Evolution Strategy
  #   - grid: Grid search (exhaustif)
  sampler: "tpe"
  
  # Stratégie de pruning (arrêt précoce)
  # Options:
  #   - median: Arrête si en-dessous de la médiane
  #   - successive_halving: Très agressif
  #   - hyperband: Équilibré
  #   - none: Pas de pruning
  pruner: "median"
  
  # Nombre de jobs parallèles
  # -1 = utiliser tous les CPU disponibles
  # 1 = séquentiel
  # N = N processus en parallèle
  n_jobs: 7
  
  # Sauvegarder les visualisations HTML
  save_plots: false
  
  # Métrique à optimiser (pour référence, géré automatiquement) : sharpe,return,drawdown
  optimize_metric: "sharpe"
  
  # Direction de l'optimisation
  direction: "maximize"

# ----------------------------------------------------------------------------
# ⚙️ GRILLE DE PARAMÈTRES À OPTIMISER
# ----------------------------------------------------------------------------
# 
# Format pour chaque paramètre:
#
# 1. Liste de valeurs discrètes:
#    param_name: [val1, val2, val3, ...]
#
# 2. Range continu (pour Optuna):
#    param_name:
#      type: "int" ou "float"
#      low: valeur_min
#      high: valeur_max
#      step: pas (optionnel pour int)
#      log: true/false (échelle logarithmique, optionnel)
#
# 3. Catégorique:
#    param_name: ["option1", "option2", "option3"]
#
# ----------------------------------------------------------------------------
param_grid:
  # Période de la moyenne mobile
  fast_ma_period:
    type: "int"
    low: 10
    high: 50
    step: 10
  #
  slow_ma_period:
    type: "int"
    low: 50
    high: 150
    step: 25
  #
  crossover_window:
    type: "int"
    low: 2
    high: 10
    step: 2
  # Période RSI
  rsi_period:
    type: "int"
    low: 7
    high: 19
    step: 3
  #
  rsi_oversold:
    type: "int"
    low: 0
    high: 60
    step: 10
  # 
  rsi_overbought:
    type: "int"
    low: 60
    high: 90
    step: 10
  #
  volume_sma_period : 
    type: "int"
    low: 10
    high: 50
    step: 10

  
    

# ----------------------------------------------------------------------------
# 🎯 PROFILS PRÉDÉFINIS
# ----------------------------------------------------------------------------
# 
# Les profils permettent de définir des configurations alternatives
# qui surchargent la configuration de base.
#
# Usage:
#   python scripts/run_optuna_from_yaml.py config.yaml --profile quick

# ----------------------------------------------------------------------------
# 📝 NOTES ET CONSEILS
# ----------------------------------------------------------------------------
#
# 1. CHOIX DU PROFIL:
#    - quick: Vérification rapide (5-10 min)
#    - dev: Développement itératif (30 min - 2h)
#    - prod: Optimisation finale (2h - 8h+)
#
# 2. NOMBRE DE TRIALS:
#    - Formule approximative: n_trials ≈ 10 × nombre_de_paramètres
#    - Pour 5 paramètres: 50-100 trials minimum
#
# 3. SAMPLER:
#    - TPE: Le meilleur choix dans 95% des cas
#    - Random: Utile pour établir une baseline
#
# 4. PRUNER:
#    - Median: Bon compromis vitesse/exploration
#    - None: Si vous avez du temps et voulez tout explorer
#
# 5. PARALLÉLISATION:
#    - n_jobs=-1: Utilise tous les CPU (recommandé)
#    - Attention: Chaque job consomme de la RAM
#
# 6. VISUALISATION DES RÉSULTATS:
#    Après l'optimisation, lancez:
#    $ optuna-dashboard sqlite:///optimization/optuna_studies/optuna.db
#    
#    Puis ouvrez http://localhost:8080 dans votre navigateur
#
# 7. DÉFINITION DES RANGES:
#    - Commencez large, puis affinez
#    - Utilisez 'log: true' pour les paramètres multiplicatifs
#    - step optionnel pour les entiers (sinon 1 par défaut)
#
# 8. GESTION MÉMOIRE:
#    Si vous manquez de RAM avec n_jobs=-1:
#    - Réduisez n_jobs à 4-8
#    - Réduisez la période de test
#    - Réduisez le nombre de symboles
#
# ============================================================================