# Configuration des Stratégies de Trading

moving_average:
  name: "Moving Average Crossover"
  description: "Stratégie basée sur le croisement de moyennes mobiles"
  parameters:
    fast_period: 50
    slow_period: 200
    timeframe: "1d"
  enabled: true

rsi:
  name: "RSI Strategy"
  description: "Stratégie basée sur l'indice de force relative"
  parameters:
    period: 14
    overbought: 70
    oversold: 30
    timeframe: "1d"
  enabled: true

macd:
  name: "MACD Strategy"
  description: "Stratégie MACD avec signal"
  parameters:
    fast_period: 12
    slow_period: 26
    signal_period: 9
    timeframe: "1d"
  enabled: true

mean_reversion:
  name: "Mean Reversion"
  description: "Stratégie de retour à la moyenne"
  parameters:
    lookback_period: 20
    entry_std: 2.0
    exit_std: 0.5
    timeframe: "1d"
  enabled: false

  
squeeze_momentum:
  name: "Squeeze Momentum"
  description: "Stratégie basée sur squeeze et breakouts"
  parameters:
    # Filtres
    min_volume_avg: 1000000
    
    # Indicateurs
    bb_period: 20
    bb_std: 2.0
    keltner_period: 20
    keltner_mult: 2.0
    atr_period: 14
    volume_period: 20
    adx_period: 14
    
    # Conditions squeeze
    min_squeeze_days: 5
    squeeze_adx_max: 20
    
    # Conditions breakout
    breakout_volume_mult: 2.0
    breakout_adx_min: 20
    
    # Gestion sorties
    target_multiplier: 2.0
    risk_per_trade: 0.02
    
    timeframe: "1d"
  enabled: true
# Configuration globale pour toutes les stratégies
global:
  max_positions: 5
  position_size_pct: 0.2  # 20% du capital par position
  stop_loss_pct: 0.05     # Stop loss à 5%
  take_profit_pct: 0.15   # Take profit à 15%
